name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
        with:
          path: my-app
      - run: ls -al
      - run: ls -al my-app


